name: images

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read
  packages: write

# Don't run more than one workflow for the same branch at a time
# This is to save credits on the CI provider
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-go-dev

jobs:
  prepare-env:
    name: detect what files changed
    runs-on: ubuntu-latest
    outputs:
      go-dev: ${{ steps.changes.outputs.go-dev }}
    steps:
      - uses: actions/checkout@v5
      - run: git config --global --add safe.directory /__w/service-images/service-images

      - name: Check for file changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # 3.0.2 https://github.com/dorny/paths-filter/releases
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            go-dev:
              - 'go/**'
              - '.github/workflows/go.yml'

  go-images:
    if: ${{ needs.prepare-env.outputs.go-dev == 'true' }}
    needs: prepare-env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required to publish or update container images in the GitHub Container Registry.

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # 3.5.0 https://github.com/docker/login-action/releases
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # 5.8.0 https://github.com/docker/metadata-action/releases
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=sha,prefix=sha-,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # 6.18.0 https://github.com/docker/build-push-action/releases
        with:
          context: ./go
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # This job is what github action will check to see if a PR is ready to
  # be merged.
  go-required-check:
    needs:
      [
        prepare-env,
        go-images,
      ]
    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
    if: always()
    runs-on: ubuntu-latest
    steps:
      # If any jobs we depend on fail, we will fail since this is a required check
      # NOTE: A timeout is considered a failure
      - name: Check for failures
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
